/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AlnTagsInput {
    'clear': () => Promise<void>;
    'hideInput': boolean;
    'readonly': boolean;
    'tags': string[];
    'tagsBelow': boolean;
  }
}

declare namespace LocalJSX {
  interface AlnTagsInput extends JSXBase.HTMLAttributes {
    'hideInput'?: boolean;
    'readonly'?: boolean;
    'tags'?: string[];
    'tagsBelow'?: boolean;
  }

  interface IntrinsicElements {
    'aln-tags-input': AlnTagsInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLAlnTagsInputElement extends Components.AlnTagsInput, HTMLStencilElement {}
  var HTMLAlnTagsInputElement: {
    prototype: HTMLAlnTagsInputElement;
    new (): HTMLAlnTagsInputElement;
  };

  interface HTMLElementTagNameMap {
    'aln-tags-input': HTMLAlnTagsInputElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

